apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: dev-ops-monitoring-project
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'null'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: 'null'
        webhook_configs:
          - url: 'http://127.0.0.1:5000'
