apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitored-app
  namespace: dev-ops-monitoring-project  # Added namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitored-app
  template:
    metadata:
      labels:
        app: monitored-app
    spec:
      containers:
      - name: monitored-app
        image: monitored-app:latest
        ports:
        - containerPort: 5000
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: monitored-app
  namespace: dev-ops-monitoring-project  # Added namespace here
spec:
  selector:
    app: monitored-app
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 8000
    targetPort: 8000
