apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: mymonitoring
data:
  grafana.ini: |
    [security]
    disable_gravatar = true

    [auth]
    disable_login_form = false
    disable_signout_menu = false
    allow_sign_up = false

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer

    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    domain = localhost
    serve_from_sub_path = false

    [users]
    default_theme = light
    auto_assign_org = true
    auto_assign_org_role = Viewer

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [auth.google]
    enabled = false
  custom.ini: |
    [grafana]
    instance_name = MyGrafana
