apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-monitoring  # Ensure this is the correct namespace
spec:
  selector:
    app: python-app  # Update this to match your app's label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # Make sure this matches the port exposed by your Python app
